match_block_trailing_comma = true
merge_imports = true
overflow_delimited_expr = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
