/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddWatcherRequest {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::ExecuteCustomActionRequestLinksWorkPackage>>,
}

impl AddWatcherRequest {
    pub fn new() -> AddWatcherRequest {
        AddWatcherRequest { user: None }
    }
}
