/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentModelLinks {
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Box<models::AttachmentModelLinksDelete>>,
    #[serde(rename = "self")]
    pub param_self: Box<models::AttachmentModelLinksSelf>,
    #[serde(rename = "container")]
    pub container: Box<models::AttachmentModelLinksContainer>,
    #[serde(rename = "author")]
    pub author: Box<models::AttachmentModelLinksAuthor>,
    #[serde(rename = "downloadLocation")]
    pub download_location: Box<models::AttachmentModelLinksDownloadLocation>,
}

impl AttachmentModelLinks {
    pub fn new(
        param_self: models::AttachmentModelLinksSelf,
        container: models::AttachmentModelLinksContainer,
        author: models::AttachmentModelLinksAuthor,
        download_location: models::AttachmentModelLinksDownloadLocation,
    ) -> AttachmentModelLinks {
        AttachmentModelLinks {
            delete: None,
            param_self: Box::new(param_self),
            container: Box::new(container),
            author: Box::new(author),
            download_location: Box::new(download_location),
        }
    }
}
