/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentsModelAllOfEmbedded {
    #[serde(rename = "elements", skip_serializing_if = "Option::is_none")]
    pub elements: Option<Vec<models::AttachmentsModelAllOfEmbeddedElementsInner>>,
}

impl AttachmentsModelAllOfEmbedded {
    pub fn new() -> AttachmentsModelAllOfEmbedded {
        AttachmentsModelAllOfEmbedded { elements: None }
    }
}
