/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BudgetModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::BudgetModelLinksSelf>,
}

impl BudgetModelLinks {
    pub fn new(param_self: models::BudgetModelLinksSelf) -> BudgetModelLinks {
        BudgetModelLinks {
            param_self: Box::new(param_self),
        }
    }
}
