/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::CollectionModelLinksSelf>,
}

impl CollectionModelLinks {
    pub fn new(param_self: models::CollectionModelLinksSelf) -> CollectionModelLinks {
        CollectionModelLinks {
            param_self: Box::new(param_self),
        }
    }
}
