/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurationModel {
    /// The maximum allowed size of an attachment in Bytes
    #[serde(
        rename = "maximumAttachmentFileSize",
        skip_serializing_if = "Option::is_none"
    )]
    pub maximum_attachment_file_size: Option<i32>,
    /// The host name configured for the system
    #[serde(rename = "hostName", skip_serializing_if = "Option::is_none")]
    pub host_name: Option<String>,
    /// Page size steps to be offered in paginated list UI
    #[serde(rename = "perPageOptions", skip_serializing_if = "Option::is_none")]
    pub per_page_options: Option<Vec<i32>>,
    /// The list of all feature flags that are active
    #[serde(rename = "activeFeatureFlags", skip_serializing_if = "Option::is_none")]
    pub active_feature_flags: Option<Vec<String>>,
}

impl ConfigurationModel {
    pub fn new() -> ConfigurationModel {
        ConfigurationModel {
            maximum_attachment_file_size: None,
            host_name: None,
            per_page_options: None,
            active_feature_flags: None,
        }
    }
}
