/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomActionModel {
    #[serde(rename = "_type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
    /// The name of the custom action
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The description for the custom action
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::CustomActionModelLinks>>,
}

impl CustomActionModel {
    pub fn new() -> CustomActionModel {
        CustomActionModel {
            _type: None,
            name: None,
            description: None,
            _links: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "CustomAction")]
    CustomAction,
}

impl Default for Type {
    fn default() -> Type {
        Self::CustomAction
    }
}
