/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DayCollectionModelAllOfEmbedded {
    /// The array of days. Each day has a name and a working status indicating if it is a working or a non-working day.
    #[serde(rename = "elements")]
    pub elements: Vec<models::DayModel>,
}

impl DayCollectionModelAllOfEmbedded {
    pub fn new(elements: Vec<models::DayModel>) -> DayCollectionModelAllOfEmbedded {
        DayCollectionModelAllOfEmbedded { elements }
    }
}
