/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DayModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::Link>,
    /// A list of resources describing why this day is a non-working day. Linked resources can be `NonWorkingDay` and `WeekDay` resources. This property is absent for working days.
    #[serde(rename = "nonWorkingReasons", skip_serializing_if = "Option::is_none")]
    pub non_working_reasons: Option<Vec<models::Link>>,
    #[serde(rename = "weekDay", skip_serializing_if = "Option::is_none")]
    pub week_day: Option<Box<models::DayModelLinksWeekDay>>,
}

impl DayModelLinks {
    pub fn new(param_self: models::Link) -> DayModelLinks {
        DayModelLinks {
            param_self: Box::new(param_self),
            non_working_reasons: None,
            week_day: None,
        }
    }
}
