/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::DocumentModelLinksSelf>,
    #[serde(rename = "project")]
    pub project: Box<models::DocumentModelLinksProject>,
    #[serde(rename = "attachments")]
    pub attachments: Box<models::DocumentModelLinksAttachments>,
}

impl DocumentModelLinks {
    pub fn new(
        param_self: models::DocumentModelLinksSelf,
        project: models::DocumentModelLinksProject,
        attachments: models::DocumentModelLinksAttachments,
    ) -> DocumentModelLinks {
        DocumentModelLinks {
            param_self: Box::new(param_self),
            project: Box::new(project),
            attachments: Box::new(attachments),
        }
    }
}
