/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponseEmbeddedDetails {
    #[serde(rename = "attribute", skip_serializing_if = "Option::is_none")]
    pub attribute: Option<String>,
}

impl ErrorResponseEmbeddedDetails {
    pub fn new() -> ErrorResponseEmbeddedDetails {
        ErrorResponseEmbeddedDetails { attribute: None }
    }
}
