/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponseEmbedded {
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Box<models::ErrorResponseEmbeddedDetails>>,
}

impl ErrorResponseEmbedded {
    pub fn new() -> ErrorResponseEmbedded {
        ErrorResponseEmbedded { details: None }
    }
}
