/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecuteCustomActionRequestLinks {
    #[serde(rename = "workPackage", skip_serializing_if = "Option::is_none")]
    pub work_package: Option<Box<models::ExecuteCustomActionRequestLinksWorkPackage>>,
}

impl ExecuteCustomActionRequestLinks {
    pub fn new() -> ExecuteCustomActionRequestLinks {
        ExecuteCustomActionRequestLinks { work_package: None }
    }
}
