/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileLinkWriteModel {
    #[serde(rename = "originData")]
    pub origin_data: Box<models::FileLinkOriginDataModel>,
    #[serde(rename = "_links")]
    pub _links: Box<models::FileLinkWriteModelLinks>,
}

impl FileLinkWriteModel {
    pub fn new(
        origin_data: models::FileLinkOriginDataModel,
        _links: models::FileLinkWriteModelLinks,
    ) -> FileLinkWriteModel {
        FileLinkWriteModel {
            origin_data: Box::new(origin_data),
            _links: Box::new(_links),
        }
    }
}
