/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileLinkWriteModelLinksOneOf1 {
    #[serde(rename = "storageUrl")]
    pub storage_url: Box<models::FileLinkWriteModelLinksOneOf1StorageUrl>,
}

impl FileLinkWriteModelLinksOneOf1 {
    pub fn new(
        storage_url: models::FileLinkWriteModelLinksOneOf1StorageUrl,
    ) -> FileLinkWriteModelLinksOneOf1 {
        FileLinkWriteModelLinksOneOf1 {
            storage_url: Box::new(storage_url),
        }
    }
}
