/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FileLinkWriteModelLinks {
    FileLinkWriteModelLinksOneOf(Box<models::FileLinkWriteModelLinksOneOf>),
    FileLinkWriteModelLinksOneOf1(Box<models::FileLinkWriteModelLinksOneOf1>),
}

impl Default for FileLinkWriteModelLinks {
    fn default() -> Self {
        Self::FileLinkWriteModelLinksOneOf(Default::default())
    }
}
