/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileLinkReadModel {
    /// File link id
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "_type")]
    pub _type: Type,
    /// Time of creation
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Time of the most recent change to the file link
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "originData")]
    pub origin_data: Box<models::FileLinkOriginDataModel>,
    #[serde(rename = "_embedded", skip_serializing_if = "Option::is_none")]
    pub _embedded: Option<Box<models::FileLinkReadModelEmbedded>>,
    #[serde(rename = "_links")]
    pub _links: Box<models::FileLinkReadModelLinks>,
}

impl FileLinkReadModel {
    pub fn new(
        id: i32,
        _type: Type,
        origin_data: models::FileLinkOriginDataModel,
        _links: models::FileLinkReadModelLinks,
    ) -> FileLinkReadModel {
        FileLinkReadModel {
            id,
            _type,
            created_at: None,
            updated_at: None,
            origin_data: Box::new(origin_data),
            _embedded: None,
            _links: Box::new(_links),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "FileLink")]
    FileLink,
}

impl Default for Type {
    fn default() -> Type {
        Self::FileLink
    }
}
