/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileLinkReadModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::FileLinkReadModelLinksSelf>,
    #[serde(rename = "storage")]
    pub storage: Box<models::FileLinkReadModelLinksStorage>,
    #[serde(rename = "container")]
    pub container: Box<models::FileLinkReadModelLinksContainer>,
    #[serde(rename = "creator")]
    pub creator: Box<models::FileLinkReadModelLinksCreator>,
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Box<models::FileLinkReadModelLinksDelete>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<models::FileLinkReadModelLinksStatus>>,
    #[serde(rename = "originOpen")]
    pub origin_open: Box<models::FileLinkReadModelLinksOriginOpen>,
    #[serde(rename = "staticOriginOpen")]
    pub static_origin_open: Box<models::FileLinkReadModelLinksStaticOriginOpen>,
    #[serde(rename = "originOpenLocation")]
    pub origin_open_location: Box<models::FileLinkReadModelLinksOriginOpenLocation>,
    #[serde(rename = "staticOriginOpenLocation")]
    pub static_origin_open_location: Box<models::FileLinkReadModelLinksStaticOriginOpenLocation>,
    #[serde(rename = "staticOriginDownload")]
    pub static_origin_download: Box<models::FileLinkReadModelLinksStaticOriginDownload>,
}

impl FileLinkReadModelLinks {
    pub fn new(
        param_self: models::FileLinkReadModelLinksSelf,
        storage: models::FileLinkReadModelLinksStorage,
        container: models::FileLinkReadModelLinksContainer,
        creator: models::FileLinkReadModelLinksCreator,
        origin_open: models::FileLinkReadModelLinksOriginOpen,
        static_origin_open: models::FileLinkReadModelLinksStaticOriginOpen,
        origin_open_location: models::FileLinkReadModelLinksOriginOpenLocation,
        static_origin_open_location: models::FileLinkReadModelLinksStaticOriginOpenLocation,
        static_origin_download: models::FileLinkReadModelLinksStaticOriginDownload,
    ) -> FileLinkReadModelLinks {
        FileLinkReadModelLinks {
            param_self: Box::new(param_self),
            storage: Box::new(storage),
            container: Box::new(container),
            creator: Box::new(creator),
            delete: None,
            status: None,
            origin_open: Box::new(origin_open),
            static_origin_open: Box::new(static_origin_open),
            origin_open_location: Box::new(origin_open_location),
            static_origin_open_location: Box::new(static_origin_open_location),
            static_origin_download: Box::new(static_origin_download),
        }
    }
}
