/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GridWriteModelLinks {
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<Box<models::GridReadModelLinksScope>>,
}

impl GridWriteModelLinks {
    pub fn new() -> GridWriteModelLinks {
        GridWriteModelLinks { scope: None }
    }
}
