/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupWriteModel {
    /// The new group name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::GroupWriteModelLinks>>,
}

impl GroupWriteModel {
    pub fn new() -> GroupWriteModel {
        GroupWriteModel {
            name: None,
            _links: None,
        }
    }
}
