/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::GroupModelLinksSelf>,
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Box<models::GroupModelLinksDelete>>,
    #[serde(rename = "updateImmediately", skip_serializing_if = "Option::is_none")]
    pub update_immediately: Option<Box<models::GroupModelLinksUpdateImmediately>>,
    #[serde(rename = "memberships", skip_serializing_if = "Option::is_none")]
    pub memberships: Option<Box<models::GroupModelLinksMemberships>>,
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::GroupModelLinksMembersInner>>,
}

impl GroupModelLinks {
    pub fn new(param_self: models::GroupModelLinksSelf) -> GroupModelLinks {
        GroupModelLinks {
            param_self: Box::new(param_self),
            delete: None,
            update_immediately: None,
            memberships: None,
            members: None,
        }
    }
}

