/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupWriteModelLinks {
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::GroupWriteModelLinksMembersInner>>,
}

impl GroupWriteModelLinks {
    pub fn new() -> GroupWriteModelLinks {
        GroupWriteModelLinks { members: None }
    }
}
