/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipFormModel {
    #[serde(rename = "_type")]
    pub _type: Type,
    #[serde(rename = "_embedded")]
    pub _embedded: Box<models::MembershipFormModelEmbedded>,
    #[serde(rename = "_links")]
    pub _links: Box<models::MembershipFormModelLinks>,
}

impl MembershipFormModel {
    pub fn new(
        _type: Type,
        _embedded: models::MembershipFormModelEmbedded,
        _links: models::MembershipFormModelLinks,
    ) -> MembershipFormModel {
        MembershipFormModel {
            _type,
            _embedded: Box::new(_embedded),
            _links: Box::new(_links),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Form")]
    Form,
}

impl Default for Type {
    fn default() -> Type {
        Self::Form
    }
}
