/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipWriteModelMeta {
    #[serde(
        rename = "notificationMessage",
        skip_serializing_if = "Option::is_none"
    )]
    pub notification_message: Option<Box<models::Formattable>>,
    /// Set to false, if no notification should get sent.
    #[serde(rename = "sendNotification", skip_serializing_if = "Option::is_none")]
    pub send_notification: Option<bool>,
}

impl MembershipWriteModelMeta {
    pub fn new() -> MembershipWriteModelMeta {
        MembershipWriteModelMeta {
            notification_message: None,
            send_notification: None,
        }
    }
}
