/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipFormModelEmbeddedValidationError {
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<Box<models::ErrorResponse>>,
    #[serde(rename = "principal", skip_serializing_if = "Option::is_none")]
    pub principal: Option<Box<models::ErrorResponse>>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Box<models::ErrorResponse>>,
}

impl MembershipFormModelEmbeddedValidationError {
    pub fn new() -> MembershipFormModelEmbeddedValidationError {
        MembershipFormModelEmbeddedValidationError {
            base: None,
            principal: None,
            roles: None,
        }
    }
}
