/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipFormModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::MembershipFormModelLinksSelf>,
    #[serde(rename = "validate")]
    pub validate: Vec<models::MembershipFormModelLinksValidateInner>,
    #[serde(rename = "commit")]
    pub commit: Box<models::MembershipFormModelLinksCommit>,
}

impl MembershipFormModelLinks {
    pub fn new(
        param_self: models::MembershipFormModelLinksSelf,
        validate: Vec<models::MembershipFormModelLinksValidateInner>,
        commit: models::MembershipFormModelLinksCommit,
    ) -> MembershipFormModelLinks {
        MembershipFormModelLinks {
            param_self: Box::new(param_self),
            validate,
            commit: Box::new(commit),
        }
    }
}
