/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipWriteModelLinks {
    #[serde(rename = "principal", skip_serializing_if = "Option::is_none")]
    pub principal: Option<Box<models::MembershipWriteModelLinksPrincipal>>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<models::MembershipReadModelLinksRolesInner>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::MembershipWriteModelLinksProject>>,
}

impl MembershipWriteModelLinks {
    pub fn new() -> MembershipWriteModelLinks {
        MembershipWriteModelLinks {
            principal: None,
            roles: None,
            project: None,
        }
    }
}
