/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipFormModelEmbedded {
    #[serde(rename = "payload")]
    pub payload: Box<models::MembershipWriteModel>,
    #[serde(rename = "schema")]
    pub schema: Box<models::MembershipSchemaModel>,
    #[serde(rename = "validationError")]
    pub validation_error: Box<models::MembershipFormModelEmbeddedValidationError>,
}

impl MembershipFormModelEmbedded {
    pub fn new(
        payload: models::MembershipWriteModel,
        schema: models::MembershipSchemaModel,
        validation_error: models::MembershipFormModelEmbeddedValidationError,
    ) -> MembershipFormModelEmbedded {
        MembershipFormModelEmbedded {
            payload: Box::new(payload),
            schema: Box::new(schema),
            validation_error: Box::new(validation_error),
        }
    }
}
