/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NonWorkingDayCollectionModelAllOfEmbedded {
    /// The array of non working days. Each day has a name and a date.
    #[serde(rename = "elements")]
    pub elements: Vec<models::NonWorkingDayModel>,
}

impl NonWorkingDayCollectionModelAllOfEmbedded {
    pub fn new(
        elements: Vec<models::NonWorkingDayModel>,
    ) -> NonWorkingDayCollectionModelAllOfEmbedded {
        NonWorkingDayCollectionModelAllOfEmbedded { elements }
    }
}
