/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NonWorkingDayModel {
    #[serde(rename = "_type")]
    pub _type: Type,
    /// Date of the non-working day.
    #[serde(rename = "date")]
    pub date: String,
    /// Descriptive name for the non-working day.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::NonWorkingDayModelLinks>>,
}

impl NonWorkingDayModel {
    pub fn new(_type: Type, date: String, name: String) -> NonWorkingDayModel {
        NonWorkingDayModel {
            _type,
            date,
            name,
            _links: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "NonWorkingDay")]
    NonWorkingDay,
}

impl Default for Type {
    fn default() -> Type {
        Self::NonWorkingDay
    }
}
