/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationCollectionModelAllOfEmbedded {
    #[serde(rename = "elements")]
    pub elements: Vec<models::NotificationModel>,
    #[serde(rename = "detailsSchemas")]
    pub details_schemas: Vec<models::SchemaModel>,
}

impl NotificationCollectionModelAllOfEmbedded {
    pub fn new(
        elements: Vec<models::NotificationModel>,
        details_schemas: Vec<models::SchemaModel>,
    ) -> NotificationCollectionModelAllOfEmbedded {
        NotificationCollectionModelAllOfEmbedded {
            elements,
            details_schemas,
        }
    }
}
