/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NotificationModelDetailsInner {
    ValuesPropertyModel(Box<models::ValuesPropertyModel>),
}

impl Default for NotificationModelDetailsInner {
    fn default() -> Self {
        Self::ValuesPropertyModel(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Values::Property")]
    ValuesColonColonProperty,
}

impl Default for Type {
    fn default() -> Type {
        Self::ValuesColonColonProperty
    }
}
