/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationCollectionModelAllOfLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::NotificationCollectionModelAllOfLinksSelf>,
    #[serde(rename = "jumpTo", skip_serializing_if = "Option::is_none")]
    pub jump_to: Option<Box<models::NotificationCollectionModelAllOfLinksJumpTo>>,
    #[serde(rename = "changeSize", skip_serializing_if = "Option::is_none")]
    pub change_size: Option<Box<models::NotificationCollectionModelAllOfLinksChangeSize>>,
}

impl NotificationCollectionModelAllOfLinks {
    pub fn new(
        param_self: models::NotificationCollectionModelAllOfLinksSelf,
    ) -> NotificationCollectionModelAllOfLinks {
        NotificationCollectionModelAllOfLinks {
            param_self: Box::new(param_self),
            jump_to: None,
            change_size: None,
        }
    }
}
