/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthClientCredentialsReadModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::OAuthClientCredentialsReadModelLinksSelf>,
    #[serde(rename = "integration")]
    pub integration: Box<models::OAuthClientCredentialsReadModelLinksIntegration>,
}

impl OAuthClientCredentialsReadModelLinks {
    pub fn new(
        param_self: models::OAuthClientCredentialsReadModelLinksSelf,
        integration: models::OAuthClientCredentialsReadModelLinksIntegration,
    ) -> OAuthClientCredentialsReadModelLinks {
        OAuthClientCredentialsReadModelLinks {
            param_self: Box::new(param_self),
            integration: Box::new(integration),
        }
    }
}
