/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthApplicationReadModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::OAuthApplicationReadModelLinksSelf>,
    #[serde(rename = "owner")]
    pub owner: Box<models::OAuthApplicationReadModelLinksOwner>,
    #[serde(rename = "integration", skip_serializing_if = "Option::is_none")]
    pub integration: Option<Box<models::OAuthApplicationReadModelLinksIntegration>>,
    #[serde(rename = "redirectUri")]
    pub redirect_uri: Box<models::OAuthApplicationReadModelLinksRedirectUri>,
}

impl OAuthApplicationReadModelLinks {
    pub fn new(
        param_self: models::OAuthApplicationReadModelLinksSelf,
        owner: models::OAuthApplicationReadModelLinksOwner,
        redirect_uri: models::OAuthApplicationReadModelLinksRedirectUri,
    ) -> OAuthApplicationReadModelLinks {
        OAuthApplicationReadModelLinks {
            param_self: Box::new(param_self),
            owner: Box::new(owner),
            integration: None,
            redirect_uri: Box::new(redirect_uri),
        }
    }
}
