/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthClientCredentialsWriteModel {
    /// OAuth 2 client id
    #[serde(rename = "clientId")]
    pub client_id: String,
    /// OAuth 2 client secret
    #[serde(rename = "clientSecret")]
    pub client_secret: String,
}

impl OAuthClientCredentialsWriteModel {
    pub fn new(client_id: String, client_secret: String) -> OAuthClientCredentialsWriteModel {
        OAuthClientCredentialsWriteModel {
            client_id,
            client_secret,
        }
    }
}
