/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedCollectionModelAllOfLinks {
    #[serde(rename = "jumpTo")]
    pub jump_to: Box<models::PaginatedCollectionModelAllOfLinksJumpTo>,
    #[serde(rename = "changeSize")]
    pub change_size: Box<models::PaginatedCollectionModelAllOfLinksChangeSize>,
}

impl PaginatedCollectionModelAllOfLinks {
    pub fn new(
        jump_to: models::PaginatedCollectionModelAllOfLinksJumpTo,
        change_size: models::PaginatedCollectionModelAllOfLinksChangeSize,
    ) -> PaginatedCollectionModelAllOfLinks {
        PaginatedCollectionModelAllOfLinks {
            jump_to: Box::new(jump_to),
            change_size: Box::new(change_size),
        }
    }
}
