/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaceholderUserCreateModel {
    /// The new name of the placeholder user to be created.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl PlaceholderUserCreateModel {
    pub fn new() -> PlaceholderUserCreateModel {
        PlaceholderUserCreateModel { name: None }
    }
}
