/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaceholderUserModelAllOfLinks {
    #[serde(rename = "showUser")]
    pub show_user: Box<models::PlaceholderUserModelAllOfLinksShowUser>,
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Box<models::PlaceholderUserModelAllOfLinksDelete>>,
    #[serde(rename = "updateImmediately", skip_serializing_if = "Option::is_none")]
    pub update_immediately: Option<Box<models::PlaceholderUserModelAllOfLinksUpdateImmediately>>,
}

impl PlaceholderUserModelAllOfLinks {
    pub fn new(
        show_user: models::PlaceholderUserModelAllOfLinksShowUser,
    ) -> PlaceholderUserModelAllOfLinks {
        PlaceholderUserModelAllOfLinks {
            show_user: Box::new(show_user),
            delete: None,
            update_immediately: None,
        }
    }
}
