/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrincipalCollectionModelAllOfEmbedded {
    #[serde(rename = "elements")]
    pub elements: Vec<models::PrincipalCollectionModelAllOfEmbeddedElementsInner>,
}

impl PrincipalCollectionModelAllOfEmbedded {
    pub fn new(
        elements: Vec<models::PrincipalCollectionModelAllOfEmbeddedElementsInner>,
    ) -> PrincipalCollectionModelAllOfEmbedded {
        PrincipalCollectionModelAllOfEmbedded { elements }
    }
}
