/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFilterModel {
    /// QueryFilter id
    #[serde(rename = "id")]
    pub id: String,
}

impl QueryFilterModel {
    pub fn new(id: String) -> QueryFilterModel {
        QueryFilterModel { id }
    }
}
