/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryOperatorModel {
    /// Query operator id
    #[serde(rename = "id")]
    pub id: String,
    /// Query operator name
    #[serde(rename = "name")]
    pub name: String,
}

impl QueryOperatorModel {
    pub fn new(id: String, name: String) -> QueryOperatorModel {
        QueryOperatorModel { id, name }
    }
}
