/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFilterInstanceSchemaModel {
    /// Describes the name attribute
    #[serde(rename = "name")]
    pub name: String,
    /// QuerySortBy name
    #[serde(rename = "filter")]
    pub filter: String,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::QueryFilterInstanceSchemaModelLinks>>,
}

impl QueryFilterInstanceSchemaModel {
    pub fn new(name: String, filter: String) -> QueryFilterInstanceSchemaModel {
        QueryFilterInstanceSchemaModel {
            name,
            filter,
            _links: None,
        }
    }
}
