/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuerySortByModel {
    /// QuerySortBy id
    #[serde(rename = "id")]
    pub id: String,
    /// QuerySortBy name
    #[serde(rename = "name")]
    pub name: String,
}

impl QuerySortByModel {
    pub fn new(id: String, name: String) -> QuerySortByModel {
        QuerySortByModel { id, name }
    }
}
