/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevisionModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::RevisionModelLinksSelf>,
    #[serde(rename = "project")]
    pub project: Box<models::RevisionModelLinksProject>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::RevisionModelLinksAuthor>>,
    #[serde(rename = "showRevision")]
    pub show_revision: Box<models::RevisionModelLinksShowRevision>,
}

impl RevisionModelLinks {
    pub fn new(
        param_self: models::RevisionModelLinksSelf,
        project: models::RevisionModelLinksProject,
        show_revision: models::RevisionModelLinksShowRevision,
    ) -> RevisionModelLinks {
        RevisionModelLinks {
            param_self: Box::new(param_self),
            project: Box::new(project),
            author: None,
            show_revision: Box::new(show_revision),
        }
    }
}
