/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemaModelLinks {
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<Box<models::SchemaModelLinksSelf>>,
}

impl SchemaModelLinks {
    pub fn new() -> SchemaModelLinks {
        SchemaModelLinks { param_self: None }
    }
}
