/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShowOrValidateFormRequest {
    #[serde(rename = "_type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "lockVersion", skip_serializing_if = "Option::is_none")]
    pub lock_version: Option<f64>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
}

impl ShowOrValidateFormRequest {
    pub fn new() -> ShowOrValidateFormRequest {
        ShowOrValidateFormRequest {
            _type: None,
            lock_version: None,
            subject: None,
        }
    }
}
