/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageCollectionModelAllOfEmbedded {
    #[serde(rename = "elements")]
    pub elements: Vec<models::StorageReadModel>,
}

impl StorageCollectionModelAllOfEmbedded {
    pub fn new(elements: Vec<models::StorageReadModel>) -> StorageCollectionModelAllOfEmbedded {
        StorageCollectionModelAllOfEmbedded { elements }
    }
}
