/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageWriteModelLinks {
    #[serde(rename = "origin")]
    pub origin: Box<models::StorageWriteModelLinksOrigin>,
    #[serde(rename = "type")]
    pub r#type: Box<models::StorageWriteModelLinksType>,
}

impl StorageWriteModelLinks {
    pub fn new(
        origin: models::StorageWriteModelLinksOrigin,
        r#type: models::StorageWriteModelLinksType,
    ) -> StorageWriteModelLinks {
        StorageWriteModelLinks {
            origin: Box::new(origin),
            r#type: Box::new(r#type),
        }
    }
}
