/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageFileUploadLinkModel {
    #[serde(rename = "_type")]
    pub _type: Type,
    #[serde(rename = "_links")]
    pub _links: Box<models::StorageFileUploadLinkModelLinks>,
}

impl StorageFileUploadLinkModel {
    pub fn new(
        _type: Type,
        _links: models::StorageFileUploadLinkModelLinks,
    ) -> StorageFileUploadLinkModel {
        StorageFileUploadLinkModel {
            _type,
            _links: Box::new(_links),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "UploadLink")]
    UploadLink,
}

impl Default for Type {
    fn default() -> Type {
        Self::UploadLink
    }
}
