/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeEntryActivityModelLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::TimeEntryActivityModelLinksSelf>,
    #[serde(rename = "projects")]
    pub projects: Vec<models::TimeEntryActivityModelLinksProjectsInner>,
}

impl TimeEntryActivityModelLinks {
    pub fn new(
        param_self: models::TimeEntryActivityModelLinksSelf,
        projects: Vec<models::TimeEntryActivityModelLinksProjectsInner>,
    ) -> TimeEntryActivityModelLinks {
        TimeEntryActivityModelLinks {
            param_self: Box::new(param_self),
            projects,
        }
    }
}
