/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeEntryCollectionModelAllOfEmbedded {
    #[serde(rename = "elements")]
    pub elements: Vec<models::TimeEntryModel>,
}

impl TimeEntryCollectionModelAllOfEmbedded {
    pub fn new(elements: Vec<models::TimeEntryModel>) -> TimeEntryCollectionModelAllOfEmbedded {
        TimeEntryCollectionModelAllOfEmbedded { elements }
    }
}
