/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateActivityRequestComment {
    #[serde(rename = "raw", skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
}

impl UpdateActivityRequestComment {
    pub fn new() -> UpdateActivityRequestComment {
        UpdateActivityRequestComment { raw: None }
    }
}
