/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCreateModel {
    #[serde(rename = "admin")]
    pub admin: bool,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "login")]
    pub login: String,
    /// The users password.  *Conditions:*  Only writable on creation, not on update.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "firstName")]
    pub first_name: String,
    #[serde(rename = "lastName")]
    pub last_name: String,
    /// The current activation status of the user.  *Conditions:*  Only writable on creation, not on update.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "language")]
    pub language: String,
}

impl UserCreateModel {
    pub fn new(
        admin: bool,
        email: String,
        login: String,
        first_name: String,
        last_name: String,
        language: String,
    ) -> UserCreateModel {
        UserCreateModel {
            admin,
            email,
            login,
            password: None,
            first_name,
            last_name,
            status: None,
            language,
        }
    }
}
