/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserModel {
    #[serde(rename = "_type")]
    pub _type: Type,
    /// The principal's unique identifier.
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    /// The principal's display name, layout depends on instance settings.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<serde_json::Value>,
    /// Time of creation
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Time of the most recent change to the user
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "_links")]
    pub _links: Box<models::UserModelAllOfLinks>,
    /// URL to user's avatar
    #[serde(rename = "avatar")]
    pub avatar: String,
    /// The user's login name  # Conditions  - User is self, or `create_user` or `manage_user` permission globally
    #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
    pub login: Option<String>,
    /// The user's first name  # Conditions  - User is self, or `create_user` or `manage_user` permission globally
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// The user's last name  # Conditions  - User is self, or `create_user` or `manage_user` permission globally
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// The user's email address  # Conditions  - E-Mail address not hidden - User is not a new record - User is self, or `create_user` or `manage_user` permission globally
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Flag indicating whether or not the user is an admin  # Conditions  - `admin`
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<bool>,
    /// The current activation status of the user.  # Conditions  - User is self, or `create_user` or `manage_user` permission globally
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// User's language | ISO 639-1 format  # Conditions  - User is self, or `create_user` or `manage_user` permission globally
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// User's identity_url for OmniAuth authentication.  # Conditions  - User is self, or `create_user` or `manage_user` permission globally
    #[serde(
        rename = "identityUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub identity_url: Option<Option<String>>,
}

impl UserModel {
    pub fn new(
        _type: Type,
        id: Option<serde_json::Value>,
        name: Option<serde_json::Value>,
        _links: models::UserModelAllOfLinks,
        avatar: String,
    ) -> UserModel {
        UserModel {
            _type,
            id,
            name,
            created_at: None,
            updated_at: None,
            _links: Box::new(_links),
            avatar,
            login: None,
            first_name: None,
            last_name: None,
            email: None,
            admin: None,
            status: None,
            language: None,
            identity_url: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "User")]
    User,
}

impl Default for Type {
    fn default() -> Type {
        Self::User
    }
}
