/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserModelAllOfLinks {
    #[serde(rename = "showUser", skip_serializing_if = "Option::is_none")]
    pub show_user: Option<Box<models::UserModelAllOfLinksShowUser>>,
    #[serde(rename = "updateImmediately", skip_serializing_if = "Option::is_none")]
    pub update_immediately: Option<Box<models::UserModelAllOfLinksUpdateImmediately>>,
    #[serde(rename = "lock", skip_serializing_if = "Option::is_none")]
    pub lock: Option<Box<models::UserModelAllOfLinksLock>>,
    #[serde(rename = "unlock", skip_serializing_if = "Option::is_none")]
    pub unlock: Option<Box<models::UserModelAllOfLinksUnlock>>,
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Box<models::UserModelAllOfLinksDelete>>,
    #[serde(rename = "authSource", skip_serializing_if = "Option::is_none")]
    pub auth_source: Option<Box<models::UserModelAllOfLinksAuthSource>>,
}

impl UserModelAllOfLinks {
    pub fn new() -> UserModelAllOfLinks {
        UserModelAllOfLinks {
            show_user: None,
            update_immediately: None,
            lock: None,
            unlock: None,
            delete: None,
            auth_source: None,
        }
    }
}
