/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionModelLinks {
    #[serde(rename = "update", skip_serializing_if = "Option::is_none")]
    pub update: Option<Box<models::VersionModelLinksUpdate>>,
    #[serde(rename = "updateImmediately", skip_serializing_if = "Option::is_none")]
    pub update_immediately: Option<Box<models::VersionModelLinksUpdateImmediately>>,
    #[serde(rename = "self")]
    pub param_self: Box<models::VersionModelLinksSelf>,
    #[serde(rename = "definingProject", skip_serializing_if = "Option::is_none")]
    pub defining_project: Option<Box<models::VersionModelLinksDefiningProject>>,
    #[serde(rename = "availableInProjects")]
    pub available_in_projects: Box<models::VersionModelLinksAvailableInProjects>,
}

impl VersionModelLinks {
    pub fn new(
        param_self: models::VersionModelLinksSelf,
        available_in_projects: models::VersionModelLinksAvailableInProjects,
    ) -> VersionModelLinks {
        VersionModelLinks {
            update: None,
            update_immediately: None,
            param_self: Box::new(param_self),
            defining_project: None,
            available_in_projects: Box::new(available_in_projects),
        }
    }
}
