/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

/// WeekDayWriteModel : Describes a week day as a working day or a non-working day (weekend).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeekDayWriteModel {
    #[serde(rename = "_type")]
    pub _type: Type,
    /// `true` for a working day. `false` for a weekend day.
    #[serde(rename = "working")]
    pub working: bool,
}

impl WeekDayWriteModel {
    /// Describes a week day as a working day or a non-working day (weekend).
    pub fn new(_type: Type, working: bool) -> WeekDayWriteModel {
        WeekDayWriteModel { _type, working }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "WeekDay")]
    WeekDay,
}

impl Default for Type {
    fn default() -> Type {
        Self::WeekDay
    }
}
