/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeekDayCollectionModelAllOfEmbedded {
    /// The array of week days.
    #[serde(rename = "elements")]
    pub elements: Vec<models::WeekDayModel>,
}

impl WeekDayCollectionModelAllOfEmbedded {
    pub fn new(elements: Vec<models::WeekDayModel>) -> WeekDayCollectionModelAllOfEmbedded {
        WeekDayCollectionModelAllOfEmbedded { elements }
    }
}
