/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeekDayCollectionModelAllOfLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::WeekDayCollectionModelAllOfLinksSelf>,
}

impl WeekDayCollectionModelAllOfLinks {
    pub fn new(
        param_self: models::WeekDayCollectionModelAllOfLinksSelf,
    ) -> WeekDayCollectionModelAllOfLinks {
        WeekDayCollectionModelAllOfLinks {
            param_self: Box::new(param_self),
        }
    }
}
