/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeekDayCollectionWriteModelEmbedded {
    /// The array of week days.
    #[serde(rename = "elements")]
    pub elements: Vec<models::WeekDayCollectionWriteModelEmbeddedElementsInner>,
}

impl WeekDayCollectionWriteModelEmbedded {
    pub fn new(
        elements: Vec<models::WeekDayCollectionWriteModelEmbeddedElementsInner>,
    ) -> WeekDayCollectionWriteModelEmbedded {
        WeekDayCollectionWriteModelEmbedded { elements }
    }
}
