/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// WeekDaySelfLinkModel : Identify a particular week day by its href.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeekDaySelfLinkModel {
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<Box<models::WeekDaySelfLinkModelSelf>>,
}

impl WeekDaySelfLinkModel {
    /// Identify a particular week day by its href.
    pub fn new() -> WeekDaySelfLinkModel {
        WeekDaySelfLinkModel { param_self: None }
    }
}
