/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WikiPageModel {
    /// Identifier of this wiki page
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The wiki page's title
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::WikiPageModelLinks>>,
}

impl WikiPageModel {
    pub fn new(title: String) -> WikiPageModel {
        WikiPageModel {
            id: None,
            title,
            _links: None,
        }
    }
}
