/*
 * OpenProject API V3 (Stable)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkPackagePatchModelLinks {
    #[serde(rename = "assignee", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<Box<models::WorkPackageModelLinksAssignee>>,
    #[serde(rename = "budget", skip_serializing_if = "Option::is_none")]
    pub budget: Option<Box<models::WorkPackageModelLinksBudget>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<models::WorkPackageModelLinksCategory>>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<models::WorkPackageModelLinksParent>>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Box<models::WorkPackageModelLinksPriority>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::WorkPackageModelLinksProject>>,
    #[serde(rename = "responsible", skip_serializing_if = "Option::is_none")]
    pub responsible: Option<Box<models::WorkPackageModelLinksResponsible>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<models::WorkPackageModelLinksStatus>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<models::WorkPackageModelLinksType>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::WorkPackageModelLinksVersion>>,
}

impl WorkPackagePatchModelLinks {
    pub fn new() -> WorkPackagePatchModelLinks {
        WorkPackagePatchModelLinks {
            assignee: None,
            budget: None,
            category: None,
            parent: None,
            priority: None,
            project: None,
            responsible: None,
            status: None,
            r#type: None,
            version: None,
        }
    }
}
